const db = [
    {
        _id:1,
        multiable_type:"USER",
        multiable_id:1,
        multimedia_path:"/abs/dsa"
    },
    {
        _id:2,
        multiable_type:"USER",
        multiable_id:2,
        multimedia_path:"/abs/dsa"
    },
    {
        _id:3,
        multiable_type:"USER",
        multiable_id:3,
        multimedia_path:"/abs/dsa"
    },
    {
        _id:4,
        multiable_type:"USER",
        multiable_id:4,
        multimedia_path:"/abs/dsa"
    },
    {
        _id:5,
        multiable_type:"USER",
        multiable_id:5,
        multimedia_path:"/abs/dsa"
    },
    {
        _id:6,
        multiable_type:"PUBLICATION",
        multiable_id:6,
        multimedia_path:"/abs/dsa"
    },
    {
        _id:7,
        multiable_type:"PUBLICATION",
        multiable_id:7,
        multimedia_path:"/abs/dsa"
    },
    {
        _id:8,
        multiable_type:"PUBLICATION",
        multiable_id:8,
        multimedia_path:"/abs/dsa"
    },
    {
        _id:9,
        multiable_type:"PUBLICATION",
        multiable_id:9,
        multimedia_path:"/abs/dsa"
    },
    {
        _id:10,
        multiable_type:"PUBLICATION",
        multiable_id:10,
        multimedia_path:"/abs/dsa"
    },                
]

export default db