export const context = {
    /* MULTIMEDIA MICROSERVICE CONNECTIONS VARS */
    MULTIMEDIA_URL: process.env.MULTIMEDIA_URL,
    MULTIMEDIA_PORT: process.env.MULTIMEDIA_PORT,
    MULTIMEDIA_BASE_ENDPOINT: process.env.MULTIMEDIA_BASE_ENDPOINT

    /* ADD ANOTHERS ENVIROMENTS VARS ... */
}