export const context = {
    /* MULTIMEDIA MICROSERVICE CONNECTIONS VARS */
    MULTIMEDIA_URL: process.env.MULTIMEDIA_URL,
    MULTIMEDIA_PORT: process.env.MULTIMEDIA_PORT,
    MULTIMEDIA_BASE_ENDPOINT: process.env.MULTIMEDIA_BASE_ENDPOINT,

    /* MULTIMEDIA MICROSERVICE CONNECTIONS VARS */
    PUBLICATION_URL: process.env.PUBLICATION_URL,
    PUBLICATION_PORT: process.env.PUBLICATION_PORT,
    PUBLICATION_BASE_ENDPOINT: process.env.PUBLICATION_BASE_ENDPOINT

    /* ADD ANOTHERS ENVIROMENTS VARS ... */
}